# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(related_name='wishlists', to='belt_exam.Product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ManyToManyField(related_name='wishlists', to='belt_exam.User'),
        ),
    ]
