# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam', '0002_auto_20180926_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
